image: python:3.5.5-jessie
pipelines:
  default:
    - step:
        script:
          - pip install -r requirements-dev.txt
          - tox
    - step:
        image: python:2.7.15-jessie
        script:
          - pip install -U pip
          - pip install -r requirements-dev.txt
          - tox
  branches:
    master:
      - step:
          script:
            - pip install -r requirements-dev.txt
            - tox
      - step:
          image: python:2.7.15-jessie
          script:
            - pip install -U pip
            - pip install -r requirements-dev.txt
            - tox
      - step:
          script:
            - pip install -r requirements-dev.txt
            - python setup.py sdist bdist_wheel
            - twine upload dist/*
