image: python:3
pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install setuptools
          - pip install -r requirements-dev.txt
          - tox
  branches:
    master:
      - step:
          caches:
            - pip
          script:
            - pip install setuptools
            - pip install -r requirements-dev.txt
            - tox
            - python setup.py sdist bdist_wheel
            - twine upload dist/*
 
