image: python:3.5-stretch
pipelines:
  default:
    - step:
        name: Check Code Style and Build Docs
        script:
          - python -m pip install flake8
          - flake8 --max-line-length=120 .
          - apt-get update
          - apt-get install -y pandoc
          - python -m pip install -r requirements-docs.txt
          - (cd docs && /usr/bin/make html)
  tags:
    v*:
      - step:
          name: Build and Deploy to PyPI
          script:
            # Install sphinx to have rst2html.py utility available
            - python -m pip install sphinx twine
            - |
              if [ "$(./get_pypi_latest_version.sh)" != "$(python setup.py --version)" ]
              then
                # Check that the long description is ready to be published on PyPI without errors
                python setup.py --long-description | rst2html.py > /dev/null 2>error.log
                if [ ! "$(cat error.log)" ]
                then
                  # Build the distribution
                  python setup.py sdist bdist_wheel
                  twine upload dist/*
                else
                  echo "Long description is incompatible with PyPI reST renderer. Check README.rst"
                  cat error.log
                  exit 1
                fi
              else
                echo "Current version is the latest version uploaded to PyPI"
                exit 1
              fi
  branches:
    master:
      - step:
          name: Unit tests for Py35
          script:
            - python -m pip install flake8
            - flake8 --max-line-length=120 .
            - apt-get update
            - apt-get install -y pandoc
            - python -m pip install -r requirements-docs.txt
            - (cd docs && /usr/bin/make html)
            - python -m pip install -r requirements-dev.txt
            - mkdir -p test-reports
            - |
              nosetests -v --cover-package=eodag\
                           --with-xunit --xunit-file test-reports/eodag_test_report_py35.xml\
                           --with-coverage --cover-xml --cover-xml-file test-reports/eodag_test_coverage_report_py35.xml\
                           --with-doctest\
                           --cover-erase\
                           --cover-inclusive\
                           --ignore-files=test_end_to_end.py\
                           eodag tests
      - step:
          name: Unit tests for Py27
          image: python:2.7-stretch
          script:
            - python -m pip install -r requirements-dev.txt
            - mkdir -p test-reports
            - |
              nosetests -v --cover-package=eodag\
                           --with-xunit --xunit-file test-reports/eodag_test_report_py27.xml\
                           --with-coverage --cover-xml --cover-xml-file test-reports/eodag_test_coverage_report_py27.xml\
                           --with-doctest\
                           --cover-erase\
                           --cover-inclusive\
                           --ignore-files=test_end_to_end.py\
                           eodag tests
