image: python:3.5.5-jessie
pipelines:
  default:
    - step:
        script:
          - apt-get install software-properties-common
          - add-apt-repository ppa:ubuntugis/ppa
          - apt-get update
          - apt-get install gdal-bin libgdal-dev
          - pip install --upgrade pip
          - pip install -r requirements-dev.txt
          - tox
  branches:
    master:
      - step:
          script:
            - apt-get install software-properties-common
            - add-apt-repository ppa:ubuntugis/ppa
            - apt-get update
            - apt-get install gdal-bin libgdal-dev
            - pip install --upgrade pip
            - pip install -r requirements-dev.txt
            - tox
            - python setup.py sdist bdist_wheel
            - twine upload dist/*
