image: python:3.5.1
pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install -r requirements-dev.txt
          - tox
          - python setup.py sdist bdist_wheel
          - twine upload dist/*
