image: python:3.5.5-jessie
pipelines:
  default:
    - step:
        name: Check Code Style and Docs
        script:
          - python -m pip install tox
          - tox -e flake8
          - tox -e docs
  tags:
    v*:
      - step:
          name: Build and Deploy to PyPI
          script:
            # Upload the distribution to PyPI if version changes
            - if [ $(./get_pypi_latest_version.sh) != $(python setup.py --version) ]
              then
                # Check that the long description may be well rendered on PyPI
                python setup.py --long-description | rst2hml > output.html
                # Build the distribution
                python setup.py sdist bdist_wheel
                twine upload dist/*
              else
                echo "Current version is already uploaded to PyPI ==> SKIP"
              fi
  branches:
    master:
      - step:
          name: Check Python 3.5 compatibility
          script:
            - python -m pip install tox
            - tox -e flake8
            - tox -e docs
            - tox -e py35
      - step:
          name: Check Python 2.7 compatibility
          image: python:2.7.15-jessie
          script:
            - python -m pip install tox
            - tox -e py27
