search:
  productType:
  footprint:
    type:
    source:
    value:
      min:
        lon:
        lat:
      max:
        lon:
        lat:
  cloudCover:
  date:
    start:
    end:
  filtering:
    filters:
      - filterName1:
          args:
            - arg1:
            - arg2:
      - filterName2:
          args:
            - arg1:

download:
  userAccount:
    id:
    password:
  destination: